<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DistributedSystem.Application\DistributedSystem.Application.csproj" />
    <ProjectReference Include="..\DistributedSystem.Persistence\DistributedSystem.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Caching\" />
    <Folder Include="Consumer\MessageBus\Consumers\Commands\" />
    <Folder Include="Consumer\UseCases\Commands\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.Newtonsoft" Version="8.3.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.2.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

</Project>
